datos <- read.table("TiemposDia1Sec.txt")
datos$V1 <- as.numeric(datos$V1)
mean(datos$V1)
install.package("MASS")
install.package("car")
install.package("fitdistrplus")
install.package("moments")
plotdist(datos$V1,histo=TRUE,demp=TRUE)
install.packages("MASS")
install.packages("car")
install.packages("fitdistrplus")
install.packages("moments")
